
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fangyuan?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8080

# mybatis:
#   config-location: classpath:config/spring/mybatis-config.xml
#   mapper-locations: classpath:config/mapper/*.xml
