
# server:
#   port: 11402

# eureka:
#   client:
#     # registerWithEureka: false
#     # fetchRegistry: false
#     service-url:
#       defaultZone: http://localhost:11401/eureka/,http://localhost:11403/eureka/
#     healthcheck:
#       enabled: true
    

#   server:
#     waitTimeInMsWhenSyncEmpty: 0
#     enable-self-preservation: false
#     eviction-interval-timer-in-ms: 20
    
    
#   instance:
#     hostname: eureka2
#     prefer-ip-address: true
#     lease-renewal-interval-in-seconds: 15
#     lease-expiration-duration-in-seconds: 30
#     instance-id: ${spring.cloud.client.ip-address}:${server.port}
 
# spring:
#   application:
#     name: eureka2

# #nohup java -jar eureka.jar --spring.profiles.active=peer1 > peer1.out &

spring:
  profiles:
    active: 
    - 11401